---
- name: Prepare Azure web server
  hosts: web
  become: true

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install basic packages
      ansible.builtin.apt:
        name:
          - curl
          - git
          - ca-certificates
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add azureuser to Docker group
      ansible.builtin.user:
        name: azureuser
        groups: docker
        append: true

    - name: Install Node Exporter
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present

    - name: Start and enable Node Exporter
      ansible.builtin.service:
        name: prometheus-node-exporter
        state: started
        enabled: true
